version: "3"

services: 
    web:
      image: 'captacion-php'
      ports: 
        - '8000:8000'
      volumes: 
        - ./:/app
      command: php artisan serve --host=0.0.0.0   
      links: 
        - 'mysql' 

    mysql:
      image: 'mysql:latest'
      ports: 
            - '3308:3306'
      environment: 
            - MYSQL_ROOT_PASSWORD=toor
      volumes: 
            - mysql-data:/var/lib/mysql
        
volumes: 
    mysql-data:        